#!/bin/sh
# PowerSmart Kenya — frontend build script (for static-host deploys, e.g. Render).
# Run from the frontend/ root directory.
#
#   VITE_API_URL=https://powersmart-api.onrender.com/api ./build.sh
#
# If VITE_API_URL is set it is baked into public/config.js before the build so
# the static site knows where the backend API lives. If it is not set, the
# existing public/config.js is left untouched (dev uses the Vite proxy instead).
set -e

if [ -n "$VITE_API_URL" ]; then
  echo "==> Baking backend API URL into public/config.js: $VITE_API_URL"
  printf '/* Generated by frontend/build.sh */\nwindow.POWERSMART_API = "%s";\n' "$VITE_API_URL" > public/config.js
fi

echo "==> Installing frontend dependencies..."
npm install --no-audit --no-fund

echo "==> Building frontend..."
npm run build

echo "==> Build complete: ./frontend/dist (serve these files from any static host)"
